interface EnvConfig {
  NEXT_PUBLIC_WEATHER_REFRESH_INTERVAL: number;
  NEXT_PUBLIC_DATA_SIZE: number;
  NEXT_PUBLIC_WEATHER_REFRESH_ENABLED: boolean;
  SUPABASE_URL: string;
  SUPABASE_ANON_KEY: string;
  SUPABASE_TABLE_NAME: string;
  NTFY_SERVER_DOMAIN?: string;
  NTFY_USERNAME: string;
  NTFY_PASSWORD: string;
  NTFY_CHANNEL_NAME: string;
  NTFY_AUTH_HEADER: string;
  DEFAULT_NTFY_URL: string;
  ANTHROPIC_API_KEY: string;
  ANTHIROPIC_MODEL: string;
  LOCATION: string;
}

const {
  NEXT_PUBLIC_WEATHER_REFRESH_INTERVAL,
  NEXT_PUBLIC_DATA_SIZE,
  NEXT_PUBLIC_WEATHER_REFRESH_ENABLED,
  SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_URL,
  SUPABASE_ANON_KEY,
  NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_TABLE_NAME,
  NTFY_SERVER_DOMAIN,
  NTFY_USERNAME,
  NTFY_PASSWORD,
  NTFY_CHANNEL_NAME,
  ANTHROPIC_API_KEY,
  ANTHIROPIC_MODEL,
  LOCATION,
} = process.env;

const NTFY_AUTH_HEADER =
  'Basic ' +
  Buffer.from(`${NTFY_USERNAME}:${NTFY_PASSWORD}`).toString('base64');

const DEFAULT_NTFY_URL = `https://${NTFY_SERVER_DOMAIN}/${NTFY_CHANNEL_NAME}`;

export const config: EnvConfig = {
  NEXT_PUBLIC_WEATHER_REFRESH_INTERVAL:
    Number(NEXT_PUBLIC_WEATHER_REFRESH_INTERVAL) || 5000,
  NEXT_PUBLIC_DATA_SIZE: Number(NEXT_PUBLIC_DATA_SIZE) || 10,
  NEXT_PUBLIC_WEATHER_REFRESH_ENABLED:
    NEXT_PUBLIC_WEATHER_REFRESH_ENABLED === 'true',
  SUPABASE_URL: SUPABASE_URL || NEXT_PUBLIC_SUPABASE_URL || '',
  SUPABASE_ANON_KEY: SUPABASE_ANON_KEY || NEXT_PUBLIC_SUPABASE_ANON_KEY || '',
  SUPABASE_TABLE_NAME: SUPABASE_TABLE_NAME || 'weather_man_weather_data',
  NTFY_SERVER_DOMAIN: NTFY_SERVER_DOMAIN || 'ntfy.sh',
  NTFY_USERNAME: NTFY_USERNAME || '',
  NTFY_PASSWORD: NTFY_PASSWORD || '',
  NTFY_CHANNEL_NAME: NTFY_CHANNEL_NAME || NTFY_USERNAME || '',
  NTFY_AUTH_HEADER: NTFY_AUTH_HEADER,
  DEFAULT_NTFY_URL: DEFAULT_NTFY_URL,
  ANTHROPIC_API_KEY: ANTHROPIC_API_KEY || '',
  ANTHIROPIC_MODEL: ANTHIROPIC_MODEL || 'claude-3-haiku-20240307',
  LOCATION: LOCATION || 'Sri Lanka',
};

export default config;
